### ISSUE TITLE
Incorrect after state event parameter when filtering for a path

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/adobe-client-data-layer#103]
Event listeners receive the `beforeState` and `afterState` as parameters, but the `afterState` parameter is incorrect when listening to a specific path, and data is appended to that path.

### Reproduce Scenario

To reproduce the issue, consider the following data layer state and event listener:
```javascript
adobeDataLayer.push({ page: { language: "en" } });
adobeDataLayer.addEventListener("adobeDataLayer:change", function(event, beforeState, afterState) {
    console.log(afterState);
}, { path: "page", scope: "future" });
```
When then adding more data to the already existing `page` path, see how the passed `afterState` is incorrect:
```javascript
adobeDataLayer.push({ page: { title: "English" } });
// logs: { title: "English" }
// should log: { language: "en", title: "English" }
```
Doing a `adobeDataLayer.getState("page")` shows the real merged state: `{ language: "en", title: "English" }`.
It would be expected that the `afterState` event parameter returns the same data as the `getState`.

### Proposed Resolution

As described also on #96, I'd remove the `beforeState` and `afterState` state parameters of the event listener, because this seems a rather advanced feature that will be tricky to support correctly while making the data layer perform well and keep the script small.

**Comment by jckautzmann** [comment]
See resolution in ticket #96
