### ISSUE TITLE
Pushing objects to update an existing array overwrites inner array 

### ISSUE THREAD

**Issue by deyu-w** [adobe/adobe-client-data-layer#111]
### Expected Behaviour
According to the [documentation](https://github.com/adobe/adobe-client-data-layer/wiki#pushing-an-object-to-update-an-existing-array), pushing objects to update an existing array would have the data appended to the inner array.

### Actual Behaviour
The data in the inner array is overwritten

#### Platform and Version
1.1.3

#### Sample Code that illustrates the problem
```
// ACDL version: 1.1.3
// push 2 items into the array 
window.adobeDataLayer = window.adobeDataLayer || [];
window.adobeDataLayer.push({
    "event": "show",
    "eventInfo": {
        "reference": "component.accordion-1-item-2"
    },
    "component": {
        "accordion-1": {
            "shownItems": [
                "component.accordion-1-item-1",
                "component.accordion-1-item-2"
            ]
        }
    }
});
// push the 3rd item into the array
window.adobeDataLayer = window.adobeDataLayer || [];
window.adobeDataLayer.push({
    "component": {
        "accordion-1": {
            "shownItems": [
                "component.accordion-1-item-3"
            ]
        }
    }
});
// computed state by running JSON.stringify(window.adobeDataLayer.getState())
"{"component":{"accordion-1":{"shownItems":["component.accordion-1-item-3","component.accordion-1-item-2"]}}}"
```

**Comment by gabrielwalt** [comment]
Arrays do get overwritten, the docs need to be corrected. The way this works in the data layer is a common JS behavior for object merges. We use lodash for the merge, and that's how it's expected to work. See example:
https://runkit.com/gabriel-walt/lodash-object-merge-example

**Comment by jckautzmann** [comment]
I updated the section about updating an existing array as follows:

One important detail to clarify is what happens when pushing data to an already existing array: it will overwrite the data of the inner array.

In the example of the `component.accordion-1.showItems` property that is an array that contains one item. If we want to modify it to contain a second item, one could push the following into the data layer:

```javascript
window.adobeDataLayer = window.adobeDataLayer || [];
window.adobeDataLayer.push({
    "component": {
        "accordion-1": {
            "shownItems": [
                "component.accordion-1-item-1",
                "component.accordion-1-item-2"
            ]
        }
    }
});
```
The new state will look as follows:
```javascript
{
    "component": {
        "accordion-1": {
            "shownItems": [
                "component.accordion-1-item-1",
                "component.accordion-1-item-2"
            ]
        }
    }
}
```
See: https://github.com/adobe/adobe-client-data-layer/wiki#pushing-an-object-to-update-an-existing-array
