### ISSUE TITLE
Loading ACDL multiple times deletes existing event listeners

### ISSUE THREAD

**Issue by bradgarropy** [adobe/adobe-client-data-layer#126]
### Expected Behaviour

Loading the ACDL script multiple times does not delete existing listeners.

### Actual Behaviour

Loading or importing the ACDL script multiple times removes existing event listeners.

### Reproduce Scenario (including but not limited to)

Both Adobe Commerce Product Recommendations and Adobe Commerce Live Search use the ACDL to track events. Each extension loads ACDL, which wipes out the other extensions event listeners.

#### Steps to Reproduce

1. Pull in ACDL using a `script` tag.
2. Set up an event listener.
3. Push the event.
4. Watch it execute the handler. 👍🏼
5. Pull in ACDL again using a `script` tag.
6. Push the event.
7. The handler is not run.

#### Platform and Version

Running in Chrome with ACDL `v2.0.1`.

#### Sample Code that illustrates the problem

Here's a [codesandbox](https://codesandbox.io/s/acdl-6uo2x)!

#### Logs taken while reproducing problem

```
CLICK EVENT
(2) [Object, Object]
  0: Object
    event: "click"
  1: Object
    event: "click"
```

**Comment by sirugh** [comment]
I'd note that duplicate loading of an identical resource is suboptimal anyways, but should still not result in broken functionality.

It would be good to provide guidance on whose responsibility it is to load the ACDL in the case of third party scripts. In our case we have a website who loads ACDL but also loads third party scripts that _also_ load ACDL.
