### ISSUE TITLE
Produce Non-Minified Artifact

### ISSUE THREAD

**Issue by klcodanr** [adobe/adobe-client-data-layer#41]
### Expected Behaviour

When using the ACDL, I would expect to be able to reference a non-minified artifact to debug / test tracking functionality. 

### Actual Behaviour

Only a minified artifact is available in /dist

### Reproduce Scenario (including but not limited to)

Install the ACDL from NPM.

#### Steps to Reproduce

In a valid node project execute:

1. `npm install @adobe/adobe-client-data-layer`
2. `ls node_modules/@adobe/adobe-client-data-layer/dist`

#### Platform and Version

NPM / 1.0.0.beta2

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

N/A

**Comment by jckautzmann** [comment]
Fixed. A non-minified version `adobe-client-data-layer.js` is generated during the build and available below the `dist` folder.
Note that this artifact is aimed for development/debug purposes and is not supported by all browers.
