### ISSUE TITLE
Asynchronous load event

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/adobe-client-data-layer#76]
As a developer, I want a data layer event that is fired when all the data has been added to the data layer, including the asynchronously loaded one, so that I can take action when all the data finished loading.

The challenge is to know when all data has finished loading and has been added to the data layer. This means that the data layer must know when all the asynchronous scripts completed their task. Therefore, a pattern is needed for async data loaders to indicate that they are still loading, and to notify when they completed, which is usually done with a Promise pattern. The data layer can then wait for the JavaScript `load` event, at which point all promises must be registered, and then wait for all the registered promises to resolve (or to time out), so that it can then trigger its own load `adobeDataLayer:load` event. And if no promises have been registered, then the data layer `adobeDataLayer:load` event can happen right after the javascript `load` event.

Some ideas of how this could work:

1. There could be a dedicated `registerLoader` method to register the functions that load asynchronous data, and like promises, when they are done, they should call the `resolve` method. The benefit of this syntax is that it doesn't reply on the `Promise` object and would therefore also work in IE:
```javascript
adobeDataLayer.push(function (dl) {
    dl.registerLoader(function (resolve) {
        jQuery.getJSON("test.json", function (data) {
            dl.push(data);
            resolve();
        });
    });
});
```

2. Returning a promise in the function that is being pushed to the data layer queue:
```javascript
adobeDataLayer.push(function (dl) {
    return new Promise(resolve => {
        jQuery.getJSON("test.json", data => {
            dl.push(data);
            resolve();
        });
    });
});
```

3. Directly pushing a promise to the data layer queue:
```javascript
adobeDataLayer.push(new Promise(resolve => {
    jQuery.getJSON("test.json", data => {
        adobeDataLayer.push(data);
        resolve();
    });
});
```

**Comment by gabrielwalt** [comment]
Another question is whether we could wait less long than for the javascript `load` event, and still be sure that all javascript loaders could have a chance to register their promises. The issue with the `load` event is that it will wait for all resourced to be fully loaded, including images, which isn't necessary in our case: we only need to wait for the scripts.

Instead, the data layer could only wait for the `DOMContentLoaded` event, because `<script>` and `<script src="...">` block the `DOMContentLoaded` event. But then we need a way for `async` and `defer` scripts that don't block the `DOMContentLoaded` event to indicate that the data layer `adobeDataLayer:load ` event should wait on them as well.

This could be done with a custom data attribute that can be added to the scripts that are loaded asynchronously. When the `DOMContentLoaded` event happens, the data layer could then search if there are such script elements, and wait for them to have loaded, and then only wait for all promises to have completed:
```html
<script src="..." defer data-layer-loader></script>
```

**Comment by jckautzmann** [comment]
IMHO the application should be responsible to fire such an event. E.g. in AEM the `cmp:loaded` event is fired when the page and the Core components are stored in the data layer.
In case there is some asynchronous processing (e.g. retrieving data on a server), the application knows best when all Promises have completed and can fire such an event. 
We may want to have a convention and call this event e.g. `adobeDataLayer:loaded`.

**Comment by jckautzmann** [comment]
Closing for now. Please reopen if needed.
