### ISSUE TITLE
Make the data layer code non-blocking

### ISSUE THREAD

**Issue by jckautzmann** [adobe/adobe-client-data-layer#8]
The data layer code currently blocks the main (single) thread. In case of high load (heavy use of the API, e.g. `push()`, `getState()` or `handle()`) this could lead to unresponsive pages and a bad user experience.
We should make sure that the code is not blocking the main browser thread.

We could solve it with e.g. Promise or Web Workers.

**Comment by gabrielwalt** [comment]
This change could be breaking implementations, so it would require a new major version of the data layer script.

**Comment by gabrielwalt** [comment]
Closing this for now as we don't see a concrete need for it as of now.
