### ISSUE TITLE
Missing dist/ folder in master branch. 

### ISSUE THREAD

**Issue by pitchmuc** [adobe/adobe-client-data-layer#87]
Hello, 

I spotted an issue for people trying to use the library directly, without the need to build it. 

### Expected Behaviour
I would like to access the minify version of the Adobe Client Data Layer

### Actual Behaviour
There is no dist/ folder in the current github state.
I would need to download the library and build the minify version of the script.

**Comment by jckautzmann** [comment]
@pitchmuc There is a note on the main README of the project with a link to the minified version:
https://unpkg.com/browse/@adobe/adobe-client-data-layer@1.0.0/dist/adobe-client-data-layer.min.js

Hope that helps.

**Comment by pitchmuc** [comment]
Thanks. I missed it.
