### ISSUE TITLE
No way to inspect the version of the Data Layer library in use.

### ISSUE THREAD

**Issue by bennet-roy** [adobe/adobe-client-data-layer#88]
### Expected Behaviour

As an end user, I should be able to inspect the current version of the Data Layer library that I am using.

### Actual Behaviour

No, variable available under the DL object which shows the version of the Data layer library in use.

No variable available to inspect the currently loaded library version.

**Comment by jckautzmann** [comment]
@bennet-roy How would you have access to the version? Here are a few options:
1. `adobeDataLayer.version`
2. `adobeDataLayer.getState('version')`

**Comment by gabrielwalt** [comment]
Since the version is going to be a static constant, I'd be for something like option 1-3.
