### ISSUE TITLE
version 1.0.1 not creating default adobeDataLayer variable

### ISSUE THREAD

**Issue by pitchmuc** [adobe/adobe-client-data-layer#89]
### Expected Behaviour

When loading the script, I would expect the adobeDataLayer object to be created if not present. 
If already present, the object should be wrapped on the 

### Actual Behaviour

if adobeDataLayer is not present, it is not being created automatically, resulting in an error if trying to use it. 

#### Steps to Reproduce

1. Load the script directly on page.

2. call the adobeDataLayer object => Issue arise. 

#### Platform and Version

version 1.0.1

#### Sample Code that illustrates the problem
On your page : 
```
<script src="/dist/adobe-client-data-layer.min.js" async></script>
<script>window.adobeDataLayer.push(function(dl) {
        // something
    });
</script>
```

**Comment by jckautzmann** [comment]
@pitchmuc The `adobeDataLayer` object is available after the script has loaded. In order to use it before the script has loaded, you need to instantiate it before using it:
```
        <script>
            window.adobeDataLayer = window.adobeDataLayer || [];
            window.adobeDataLayer.push({ "test1": "Hello World" });
        </script>
        <script src="js/adobe-client-data-layer.min.js" async defer></script>
```
This is explained at:
https://github.com/adobe/adobe-client-data-layer/wiki#setup
