### ISSUE TITLE
Incorrect before state event parameter for past events

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/adobe-client-data-layer#96]
Event listeners receive the `beforeState` and `afterState` as parameters, but these are incorrect when listening to a specific path and multiple events past events happened.

### Reproduce Scenario

```javascript
adobeDataLayer.push({"event": "zero", "data": "0" });
adobeDataLayer.push({"event": "one", "data": "1" });
adobeDataLayer.push({"event": "two", "data": "2" });
adobeDataLayer.addEventListener("one", function(event, beforeState, afterState) {
    console.log(event, beforeState, afterState);
}, { "path": "data" });
// logs: {event: "one", data: "1"} "1" "1"
// should log: {event: "one", data: "1"} "0" "1"
```

### Proposed Resolution

I'd remove the `beforeState` and `afterState` state parameters of the event listener, because this seems a rather advanced feature that will be tricky to support correctly while making the data layer perform well and keep the script small. In theory this would be a breaking change, but these parameters are only passed when filtering with a `path` option, which in itself is another bug, at least from what is documented: "The state before the change caused by the event is available when the event object has data that modify the state." Therefore, it is unlikely that anybody already uses relies on that feature, and it should be safe to simplify the data layer by removing these parameters altogether.

**Comment by gabrielwalt** [comment]
A further inconsistency of the `after` event parameter is that it doesn't always return the real merged state that the data layer contains after the event.

To reproduce the issue, consider the following data layer state and event listener:
```javascript
adobeDataLayer.push({ page: { language: "en" } });
adobeDataLayer.addEventListener("adobeDataLayer:change", function(event, before, after) {
    console.log(after);
}, { path: "page", scope: "future" });
```
When then adding more data to the already existing `page` path, see how the passed `after` state is incorrect:
```javascript
adobeDataLayer.push({ page: { title: "English" } });
// logs: { title: "English" }
// should log: { language: "en", title: "English" }
```
Doing a `adobeDataLayer.getState("page")` shows the real merged state: `{ language: "en", title: "English" }`.
It would be expected that the `after` event parameter returns the same data as the `getState`.

**Comment by jckautzmann** [comment]
Following options have been proposed to fix this issue:
1) the before and the after states of an item are computed by replaying the history of all the data items that have been pushed to the data layer array and merging the state until the given item. See PR #104 .
2) each item keeps a copy of its state before and after it is merged to the data layer state. See PR #105 

Option #1 might heavily impact the processing performance, especially when the data layer has a large history of pushed items.
Option #2 reduces the cost of processing the before/after states as the state at the time we push an item can be read from an item property. But it increases the memory footprint as it is keeping all the past states.

As it is a rather advanced feature that might not be widely used and as the options to fix it would have some negative impact on the performance (either high processing or high memory footprint) we will remove the `beforeState` and `afterState` state parameters of the event listener.

**Comment by jckautzmann** [comment]
> we will remove the beforeState and afterState state parameters of the event listener
This was done with PR #113
